### ISSUE TITLE
Add dirt, leaves and grass

### ISSUE THREAD

**Issue by jmespadero** [jmespadero/cityGen#2]
Add small objects as dirt, dry leaves and small pieces of grass inside the city.

**Comment by jmespadero** [comment]
Here is a good source for textures of drylLeaves
http://www.plaintextures.com/leavestextures.php?urlcode=4OFp0fyJuQk7kECwARlGQI6gXc23C6J1Ilki9bYTRbCosIoRe0JjM3tZoWNuHt9z1j7X1AttfETMolQ0MvKZXw%3D%3D

If any used, please ensure the source is correctly referenced and acknowledged.

**Comment by sergiofv93** [comment]
Hi @jmespadero,

I need to know how to access to a map of the city with the vertex and regions numbers. Only possible on Blender?
I mean, would be useful to have a 2D file with the city 2D map.
Where is it? Or I have to develop it?

Thanks in advance,
greetings!

**Comment by sergiofv93** [comment]
I mean, something like this, with vertex/regions numbers display:

![citymap2d](https://user-images.githubusercontent.com/22729865/30802765-dc6d49c2-a1e7-11e7-86a0-dd019ac0ee5e.png)

Thanks in advance,
greetings!

**Comment by jmespadero** [comment]
The image you need is an SVG image named `city.map.verbose.svg`, which is generated every time you execute the cityGen2D.py script.
If you need to generate such .svg file again, search the "log" value in the file `city.data.json` and launch again cityGen2D.py with the same  values.

For example, for current file I see the `log` line:
```
"log":"-s 10 -r 150.000000 --randomSeed 46529 2017-09-22 11:03:55.203461"
```

Then launch the generator again with the same arguments:
```
python3 ./cityGen2D.py -s 10 -r 150.000000 --randomSeed 46529
```
You should see a file like this:
![city map verbose](https://user-images.githubusercontent.com/6451497/30803684-d0a1160c-a1ea-11e7-97f0-e5e8e7609fc8.png)

**Comment by sergiofv93** [comment]
Hi @jmespadero ,

I have implemented a basic algorithm to locate the leaves on the map correctly. They already are not placed in the internal regions surrounded by the houses line, but I have to upgrade the algorithm, because I can't locate them in the same location than the curbs.

For now, this is the progress:
![leaveslocation](https://user-images.githubusercontent.com/22729865/31854389-8535e64e-b698-11e7-99d0-22bd2b85d0bc.png)

What's more, the algorithm is too slow. I need it to be faster. For each leaf I test if it is in a correct position. If not, I delete it and create a new leaf in a random location.

Some idea to make it faster?

Thanks in advance,
greetings.

**Comment by jmespadero** [comment]
Of course...

First you need to determine if the algorithm is slow because the randomness makes you discard too many leaves, or just because it is coded slow. Have you a ratio of how many leaves you keep and how many you discard after generating 1.000 leaves?


To me, the ideal is to discard no more than 10 positions of every 1000 leaves. If you have more, it is better to use another approach. For example, instead of generate random (x,y) positions and test them for every street, you can generate N random points in [0..1, 0..1], and convert it to valid coordinates using the corners of a region in a way similar to [trilinear coordinates](https://en.wikipedia.org/wiki/Trilinear_coordinates) ...

 One simple way is this: Take two corners of a region (A, B) and the seed of the region (C)
![citygenstreet](https://user-images.githubusercontent.com/6451497/31879055-694e3e50-b7dc-11e7-8018-d9b21ea65c37.png)

Generate a random number **r1** in [0..1] and compute point D = (1-r1) * A + r1 * B.
Then, generate a random number **r2** in [0..1] and compute point E = (1-r2) * D + r2 * C.
![citygenstreet](https://user-images.githubusercontent.com/6451497/31929615-06a680a2-b89d-11e7-8a7c-f561d963a40e.png)
You want  to place the leaf at E

The advantage of this is that  you can "tune" r1 and r2. For example, any r2 > 0.5 will surely produce a E point inside a house, so you can generate r2 in [0 .. 0.3] instead of [0..1].
You can also avoid collision in leaves if you don't choose r1 as N random numbers in [0..1] , but as
 i /N + random (-1/2N..1/2N), so they distribute along the street.

 Can you please post the number of leaves you discard after generating 1000 random leaves?

**Comment by sergiofv93** [comment]
The number of leaves I'm discarting is random. Sometimes a leaf is correctly located at first time, but sometimes it could be generating 15 - 20 leaves and discarting them before creating a leaf in a correct position.

It's because each leaf has to proof random locations in the whole map, and the percentage of "street-floor" is quite low. So, statistically, a leaf generates more incorrect positions than valid positions.

**Comment by jmespadero** [comment]
That's the reason you should not "choose random position and check if they are valid", but "create valid position from random numbers".

**Comment by sergiofv93** [comment]
Okey, thanks a lot. I will try it and post any changes.

Greetings!!

**Comment by sergiofv93** [comment]
I have done a pull request #13

**Comment by jmespadero** [comment]
Thanks. I will close this issue.
