### ISSUE TITLE
Set current working Directory

### ISSUE THREAD

**Issue by jmespadero** [jmespadero/cityGen#5]
There is a problem with CWD in windows, so blender libraries (cg-library.blend, cg-monsters.blend) are not found even if they are in the same directory.
Please, check and solve value of current working directory.

**Comment by sergiofv93** [comment]
Hi @jmespadero ,

It seems like the bug has been solved. Now I can run the application over Windows 10 and Linux.

The main fix was to change the implementation of the loading of files as internal files for the resulting output.blend. The specific code line was in the cityGen3D.py file, and it was:
`bpy.data.texts.load(inputFilename, True)`

It seems to be a Blender bug that prevents to load the file correctly in Windows, but it works properly over Linux.

It was changed by the next code, which works fine:
`if inputFilename in bpy.data.texts:`
`    bpy.data.texts.remove(bpy.data.texts[inputFilename])`
`createInternalText(inputFilename)`

It means that, instead of loading the file as internal file, the code creates a new internal file and adds it to the resulting output.

Kind regards.
